export const ADD_TO_CARD = "ADD_TO_CARD";
export const REMOVE_FROM_CARD = "REMOVE_FROM_CARD";
export const LOAD_PRODUCT = "LOAD_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const SEARCH_CLEAR = "SEARCH_CLEAR";

export const LOGIN_USER = "LOGIN_USER";
export const REGISTER_USER = "REGISTER_USER";
export const LOGOUT = "LOGOUT";
